from game.model.Resources import Resources
from model.List import List
from random import random

class _Facility :
	"""
	This abstract class represents a facility which can be built buy a player.
	A facility can generate resources each turn, or give special actions (by checking if the player's facilities' list
	contains a certain instance of object).
	"""

	def __init__(self, name : str, cost : Resources|None, gain : Resources|int|None, frequency : int) :
		self.name = name
		self.cost = cost
		self.gain = gain
		self.frequency = frequency
		
		self.state = 0
	
	def promptSummary(self) -> None :
		"""
		Prompts resumed informations about the facility
		"""
		print(f"{self.name.ljust(20)}{self.state}/{self.frequency}")

	def promptDetails(self) -> None :
		"""
		Prompts detailed informations about the facility
		"""
		print(
			f"\nCoût :                    [ {self.cost}]\n"
			f"Gain :                    [ {self.gain}] / {self.frequency} tour(s)\n"
		)
	
	def getGain(self) -> Resources|int|None :
		"""
		Returns the resources or abstract value generated by this facility.
		"""
		if self.frequency != 0 :
			if self.state == self.frequency :
				self.state = 1
				return self.gain
			else :
				self.state += 1
				return None

class _NonRentableFacility(_Facility) :

	def __init__(self, name : str, cost : Resources|None) :
		super().__init__(name, cost, None, 0)
	
	def getGain(self) -> Resources|int|None :
		return None

class Farm(_Facility) :

	def __init__(self) :
		super().__init__("Ferme", Resources(food=1, wood=2), Resources(food=6), 3)

class Habitation(_Facility) :

	def __init__(self) :
		super().__init__("Habitation", Resources(wood=2), None, 0)
		self.given = False
	
	def getGain(self) -> Resources|int|None :
		if not self.given :
			self.given = True
			return 4
		return None

class Baracks(_NonRentableFacility) :

	def __init__(self) :
		super().__init__("Caserne", Resources(stone=2, wood=4))
		self.troups = 0

class Mine(_Facility) :

	def __init__(self) :
		super().__init__("Mine", Resources(wood=4), None, 2)
		self.stoneRatio = (random() * 10) % 5 + 1
		self.ironRatio = (random() * 10) % 5 + 1

	def getGain(self) -> Resources|int|None :
		return Resources(stone=self.stoneRatio, iron=self.stoneRatio)

class Forge(_NonRentableFacility) :

	def __init__(self) :
		super().__init__("Forge", Resources(stone=6))

class Sawmill(_Facility) :

	def __init__(self) :
		super().__init__("Scierie", Resources(wood=6, iron=1), Resources(wood=3), 1)

class HunterHood(_Facility) :

	def __init__(self) :
		super().__init__("Ferme", Resources(wood=2), Resources(food=1), 1)

class Temple(_Facility) :

	def __init__(self) :
		super().__init__("Temple", Resources(stone=4), Resources(knowledge=2), 1)

class Altar(_NonRentableFacility) :

	def __init__(self) :
		super().__init__("Autel", Resources(stone=3, iron=1))